config/routes.rb
require 'sidekiq/web'

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
end if Rails.env.production?

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/docs'
  mount Rswag::Api::Engine => '/docs'
  
  mount Sidekiq::Web => "/sidekiq"
  mount PgHero::Engine, at: "pghero"

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :registries, only: [:index]
      resources :jobs do
        collection do
          get :index, to: 'jobs#create'
        end
      end
    end
  end

  get '/resolve', to: 'jobs#resolve', as: :resolve

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal'
  
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @registries = Registry.all.order(:name)
  end
end

app/views/home/index.html.erb
<div class="col-lg-4 container-sm text-center">
  <form class="row g-2 justify-content-center" action='<%= resolve_path %>'>
      <%= select_tag "registry", options_from_collection_for_select(@registries, "name", "name"), class: "form-select", include_blank: 'Select registry...' %>
      <input name='package_name' type="text" class="form-control" id="package_name" placeholder="Package Name: eg rails" size="20" required>
      <input name='version' type="text" class="form-control" id="version" placeholder="Version (optional)" size="20">
      <input name='before' type="text" class="form-control" id="before" placeholder="Before date-time (optional)" size="20">
      <button type="submit" class="btn btn-primary mb-3">Resolve</button>
  </form>
</div>